# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  lane :tests do
    run_tests(workspace: "../source/iOSStarterProject.xcworkspace",
              devices: ["iPhone X"],
              scheme: "iOSStarterProject")
  end

  desc "Cleanup Xcode directories"
  lane :clean_xcode do
    `rm -rf ~/Library/Developer/Xcode/DerivedData/*`
    `rm -rf ~/Library/Developer/Xcode/Archives/*`
    `rm -rf ../build/out/*`
  end
end
